### ISSUE TITLE
Add To-do App in Compose 

### ISSUE THREAD

**Issue by OmkarBhostekar** [yogeshpaliyal/Play-With-Compose#1]

**Comment by OmkarBhostekar** [comment]
Can I work on this feature ?

**Comment by OmkarBhostekar** [comment]
@yogeshpaliyal hacktoberfest 2021 showing this project is not participating.

**Comment by yogeshpaliyal** [comment]
Yes, there is a issue from my side, that is resolved it will reflect in some time

**Comment by OmkarBhostekar** [comment]
@yogeshpaliyal okay no problem.

**Comment by yogeshpaliyal** [comment]
@OmkarBhostekar  Is your PR, added on Hacktoberfest website?

**Comment by OmkarBhostekar** [comment]
@yogeshpaliyal yeah, PR is added in hacktoberfest website
