### ISSUE TITLE
Add Clubhouse Clone UI

### ISSUE THREAD

**Issue by V9vek** [yogeshpaliyal/Play-With-Compose#5]
Can i work on this?

**Comment by yogeshpaliyal** [comment]
Yes, sure

**Comment by V9vek** [comment]
Opened a pull request, please check and kindly add required tag for HacktoberFest

**Comment by yogeshpaliyal** [comment]
Pull request merged and it will reflect on the HacktoberFest website in some time. 🚀 🥳

**Comment by V9vek** [comment]
Okay thanks ☺️
